### ISSUE TITLE
Angular exception issue

### ISSUE THREAD

**Issue by fizerkhan** [csnover/TraceKit#12]
Angular gives exception with `stack` string as 

```
"ReferenceError: $firebase is not defined
    at new <anonymous> (http://localhost:3474/scripts/controllers/headers/show-controller.js:3:20)
    at d (http://localhost:3474/scripts/vendor/angular.min.js:30:452)
    at Object.instantiate (http://localhost:3474/scripts/vendor/angular.min.js:31:80)
    at $get (http://localhost:3474/scripts/vendor/angular.min.js:62:33)
    at link (http://localhost:3474/scripts/vendor/angular-route.min.js:7:208)
    at H (http://localhost:3474/scripts/vendor/angular.min.js:49:375)
    at f (http://localhost:3474/scripts/vendor/angular.min.js:42:399)
    at http://localhost:3474/scripts/vendor/angular.min.js:42:67
    at $get.m (http://localhost:3474/scripts/vendor/angular.min.js:43:303)
    at A (http://localhost:3474/scripts/vendor/angular.min.js:47:46)"
```

When i compute stacktrace using `TraceKit.computeStackTrace(exception)`, the result `stack` array does not include first line 

```
    at new <anonymous> (http://localhost:3474/scripts/controllers/headers/show-controller.js:3:20)
```

I could see the first line has two word for `function` name. Will that be problem?

**Comment by niemyjski** [comment]
I'll try and add a test for this.

**Comment by niemyjski** [comment]
This should now be fixed in the latest build: https://github.com/csnover/TraceKit/blob/master/tracekit.js#L636

**Comment by fizerkhan** [comment]
@niemyjski  Thanks. I will check.
